/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import facade.FacadeCurso;
import model.Curso;
import model.Modalidade;
import swing.model.ModalidadeComboBoxModel;

/**
 *
 * @author everaldo
 */
public class AtualizarCursoUI extends javax.swing.JFrame {

    /**
     * Creates new form AtualizarCursoUI
     */
    public AtualizarCursoUI(SistemaAcademicoUI telaPrincipal, Curso curso) {
        super();
        this.telaPrincipal = telaPrincipal;
        this.curso = curso;
        initComponents();
        cursoIdTextField.setText(Long.toString(curso.getId()));
        cursoNomeTextField.setText(curso.getNome());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelarBotao = new javax.swing.JButton();
        alterarBotao = new javax.swing.JButton();
        cursoIdLabel = new javax.swing.JLabel();
        cursoIdTextField = new javax.swing.JTextField();
        cursoNomeLabel = new javax.swing.JLabel();
        cursoNomeTextField = new javax.swing.JTextField();
        cursoModalidadeLabel = new javax.swing.JLabel();
        modalidadeComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Atualizar Curso"));

        cancelarBotao.setText("Cancelar");
        cancelarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotaoActionPerformed(evt);
            }
        });

        alterarBotao.setText("Alterar");
        alterarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarBotaoActionPerformed(evt);
            }
        });

        cursoIdLabel.setText("Id:");

        cursoIdTextField.setEditable(false);
        cursoIdTextField.setBackground(new java.awt.Color(204, 204, 204));

        cursoNomeLabel.setText("Nome:");

        cursoModalidadeLabel.setText("Modalidade:");

        modalidadeComboBox.setModel(new ModalidadeComboBoxModel());
        modalidadeComboBox.setSelectedIndex(curso.getModalidade().ordinal());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cursoModalidadeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 188, Short.MAX_VALUE)
                                .addComponent(alterarBotao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelarBotao))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(modalidadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cursoNomeLabel)
                            .addComponent(cursoIdLabel))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cursoNomeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(cursoIdTextField))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cursoIdLabel)
                    .addComponent(cursoIdTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cursoNomeLabel)
                    .addComponent(cursoNomeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alterarBotao)
                            .addComponent(cancelarBotao))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modalidadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cursoModalidadeLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotaoActionPerformed
        fecharTela();
    }//GEN-LAST:event_cancelarBotaoActionPerformed

    private void alterarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarBotaoActionPerformed
        String nomeCurso = cursoNomeTextField.getText();
        Modalidade modalidade = (Modalidade) modalidadeComboBox.getSelectedItem();
        curso.setNome(nomeCurso);
        curso.setModalidade(modalidade);
        FacadeCurso.alterar(curso);
        telaPrincipal.atualizarTabela();
        fecharTela();
    }//GEN-LAST:event_alterarBotaoActionPerformed

    private void fecharTela(){
        //LEMBRE-SE de trocar EXIT ON CLOSE PARA DISPOSE :-)
        setVisible(false);
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */


    Curso curso;
    SistemaAcademicoUI telaPrincipal;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarBotao;
    private javax.swing.JButton cancelarBotao;
    private javax.swing.JLabel cursoIdLabel;
    private javax.swing.JTextField cursoIdTextField;
    private javax.swing.JLabel cursoModalidadeLabel;
    private javax.swing.JLabel cursoNomeLabel;
    private javax.swing.JTextField cursoNomeTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<Modalidade> modalidadeComboBox;
    // End of variables declaration//GEN-END:variables
}
